<!DOCTYPE html>
<html>
<head>
<title>My Example</title>

<script src="\\\\meet\File Share\Meet's Data\Link Fixer\JS\Ext _JS.Js"></script>
<a href="\\meet\File Share\Meet's Data\Link Fixer\JS\Ext _JS.Js">Click Here to View Report  for Ext _JS <a/>
</head>
<body>

<button onClick="JavaScript:exampleFunction()">Click Me</button>
<hyperlink onClick="JavaScript:exampleFunction()"> Click Me </hyperlink>  

</body>
</html>