<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="css/index.css">
        <link rel="script" type="text/javascript" href="js/tagline.js">
        <title>Hello Cimconites</title>
         <link rel="stylesheet" href="styles.css">
    <script src="\\meet\FS_M\REG-1\1\Report Feb -2023.xlsx">showTagline();</script>
    </head>
    <body>
        <header>
            <div class="container">
                <h1><a href="/">HELLO <BR>CIMCONITES </a></h1>
<P>
<a href="\\meet\FS_M\REG-1\1\Report Jan -2023.xlsx">Click Here to View Report January <a/>
                <span id="tagline">
                    <script src="js/Ext _JS.Js">showTagline();</script>
                </span>
            </div>
        </header>
    </body>
</html>